repos:
  - repo: local
    hooks:
      - id: swiftlint
        name: SwiftLint
        entry: swiftlint autocorrect
        language: system
        files: \.(swift)$
        args: ['lint', '--config', 'swiftlint.yml']

      - id: swiftformat
        name: SwiftFormat
        entry: swiftformat --swiftversion 5.10
        language: system
        files: \.(swift)$
        types: [file]

